[package]
name = "blacksmith"
version = "0.1.0"
authors = ["Malkaviel - Maxime Capuano <maxime.capuano2@gmail.com>"]
publish = false #don't publish it for the moment
description = "Experimental game engine"
license = "MIT"
repository = "https://github.com/Malkaviel/Blacksmith_GameEngine.git"

[dependencies]
blacksmith_core = { path = "blacksmith_core"}
blacksmith_subsystems = { path = "blacksmith_subsystems"}
blacksmith_gameplay = { path = "blacksmith_gameplay"}

[workspace]