[package]
name = "kindred_engine"
version = "0.1.0"
authors = ["Malkaviel - Maxime Capuano <maxime.capuano2@gmail.com>"]
publish = false #don't publish it for the moment
description = "Experimental game engine"
license = "MIT"
repository = "https://github.com/Malkaviel/KindredEngine.git"

[dependencies]
cgmath = "0.15.0"
rand = "0.3"