[package]
name = "blacksmith_game_engine"
version = "0.1.0"
authors = ["Malkaviel - Maxime Capuano <maxime.capuano2@gmail.com>"]
publish = false #don't publish it for the moment
description = "Experimental game engine"
license = "Apache-2.0"
repository = "https://github.com/Malkaviel/Blacksmith_GameEngine.git"

[dependencies]
cgmath = "0.15.0"
rand = "0.3"
rayon = "0.9.0"
remove_dir_all = "0.3.0"
app_dirs = "1.1.1"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"