[package]
name = "maskerad_subsystems"
version = "0.1.0"
authors = ["Maxime Capuano <maxime.capuano2@gmail.com>"]

[dependencies]
rayon = "0.9.0"
remove_dir_all = "0.3.0"
app_dirs = "1.1.1"
maskerad_core = { path = "../maskerad_core"}